#ifndef UTILS_ANSI
#define UTILS_ANSI

#define ANSI_RESET                  "\x1B[0m"
#define ANSI_TEXT_BOLD              "\x1B[1m"
#define ANSI_TEXT_ITALIC            "\x1B[3m"
#define ANSI_TEXT_UNDERLINE         "\x1B[4m"
#define ANSI_TEXT_CONCEAL           "\x1B[8m"
#define ANSI_TEXT_CROSSED_OUT       "\x1B[9m"
#define ANSI_TEXT_UNDERLINE_OFF     "\x1B[24m"
#define ANSI_TEXT_REVEAL            "\x1B[28m"
#define ANSI_TEXT_BLACK             "\x1B[30m"
#define ANSI_TEXT_RED               "\x1B[31m"
#define ANSI_TEXT_GREEN             "\x1B[32m"
#define ANSI_TEXT_YELLOW            "\x1B[33m"
#define ANSI_TEXT_BLUE              "\x1B[34m"
#define ANSI_TEXT_MAGENTA           "\x1B[35m"
#define ANSI_TEXT_CYAN              "\x1B[36m"
#define ANSI_TEXT_WHITE             "\x1B[37m"
#define ANSI_TEXT_GRAY              "\x1B[90m"
#define ANSI_TEXT_BRIGHT_RED        "\x1B[91m"
#define ANSI_TEXT_BRIGHT_GREEN      "\x1B[92m"
#define ANSI_TEXT_BRIGHT_YELLOW     "\x1B[93m"
#define ANSI_TEXT_BRIGHT_BLUE       "\x1B[94m"
#define ANSI_TEXT_BRIGHT_MAGENTA    "\x1B[95m"
#define ANSI_TEXT_BRIGHT_CYAN       "\x1B[96m"
#define ANSI_TEXT_BRIGHT_WHITE      "\x1B[97m"
#define ANSI_BG_BLACK               "\x1B[40m"
#define ANSI_BG_RED                 "\x1B[41m"
#define ANSI_BG_GREEN               "\x1B[42m"
#define ANSI_BG_YELLOW              "\x1B[43m"
#define ANSI_BG_BLUE                "\x1B[44m"
#define ANSI_BG_MAGENTA             "\x1B[45m"
#define ANSI_BG_CYAN                "\x1B[46m"
#define ANSI_BG_WHITE               "\x1B[47m"
#define ANSI_BG_GRAY                "\x1B[100m"
#define ANSI_BG_BRIGHT_RED          "\x1B[101m"
#define ANSI_BG_BRIGHT_GREEN        "\x1B[102m"
#define ANSI_BG_BRIGHT_YELLOW       "\x1B[103m"
#define ANSI_BG_BRIGHT_BLUE         "\x1B[104m"
#define ANSI_BG_BRIGHT_MAGENTA      "\x1B[105m"
#define ANSI_BG_BRIGHT_CYAN         "\x1B[106m"
#define ANSI_BG_BRIGHT_WHITE        "\x1B[107m"

#endif